#!/bin/sh
# Standalone luau has no file I/O, so every fixture under tests/fixtures is embedded into the
# generated (gitignored) module tests/fixtures/generated.luau, which tests/lib/fixtures.luau
# loads. Regenerate after adding or changing fixtures: `make fixtures` (or
# `sh scripts/fixtures/embed.sh`).
#
# Keys are paths relative to tests/fixtures ("prometheus/3.15.0/query_vector.json",
# "MANIFEST.tsv"). Text goes verbatim into a long bracket string. Anything a long bracket would
# alter (NUL, CR, which Luau normalises, or a leading newline, which it drops) and every binary
# capture (PNG) goes into the `base64` table instead; tests/lib/fixtures.luau decodes it, so
# reads are byte-exact either way. The output is stylua-, selene- and luau-lsp-clean.
set -eu

cd "$(dirname "$0")/../.."

dir=tests/fixtures
out=$dir/generated.luau
tmp="$out.tmp.$$"
list="$out.list.$$"
trap 'rm -f "$tmp" "$list"' EXIT INT TERM

[ -d "$dir" ] || mkdir -p "$dir"

find "$dir" -type f ! -name 'README.md' ! -name '.*' ! -name 'generated.luau' ! -name 'generated.luau.*' |
	LC_ALL=C sort >"$list"

while IFS= read -r f; do
	case ${f#"$dir"/} in
	*\"* | *\\*)
		echo "embed.sh: unsupported character in fixture path: $f" >&2
		exit 1
		;;
	esac
done <"$list"

is_binary() {
	case $1 in
	*.png | *.pb | *.bin) return 0 ;;
	esac
	[ "$(head -c 1 "$1" | od -An -tu1 | tr -d ' ')" = 10 ] && return 0
	# shellcheck disable=SC2094 # both sides only read the file
	LC_ALL=C tr -d '\000\r' <"$1" | cmp -s - "$1" || return 0
	return 1
}

# emit_table NAME TYPE MODE: MODE "text" embeds text files, "base64" the others.
emit_table() {
	entries=0
	while IFS= read -r f; do
		if is_binary "$f"; then kind=base64; else kind=text; fi
		[ "$kind" = "$3" ] || continue
		[ "$entries" -gt 0 ] || printf 'local %s: %s = {\n' "$1" "$2"
		entries=$((entries + 1))
		key=${f#"$dir"/}
		if [ "$kind" = base64 ]; then
			printf '\t["%s"] = "%s",\n' "$key" "$(base64 <"$f" | tr -d '\n')"
		else
			# "]=" (not "]=]") so a file ending in "]=" cannot close the string early.
			eq="="
			while grep -qF "]$eq" "$f"; do
				eq="$eq="
			done
			printf '\t["%s"] = [%s[\n' "$key" "$eq"
			cat "$f"
			printf ']%s],\n' "$eq"
		fi
	done <"$list"
	if [ "$entries" -gt 0 ]; then
		printf '}\n'
	else
		printf 'local %s: %s = {}\n' "$1" "$2"
	fi
}

{
	printf -- '--!strict\n'
	# shellcheck disable=SC2016 # literal backticks
	printf -- '-- GENERATED by scripts/fixtures/embed.sh; do not edit. Run `make fixtures`.\n'
	emit_table files '{ [string]: string }' text
	emit_table base64 '{ [string]: string }' base64
	printf 'return { files = files, base64 = base64 }\n'
} >"$tmp"

mv "$tmp" "$out"
trap - EXIT INT TERM
rm -f "$list"
